name: Extract PDF data

on:
  workflow_run:
    workflows: ["Process official CSV"]
    types:
      - completed

jobs:
  build:
    name: Extract data from PDF to CSV
    runs-on: macos-10.15

    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install requests BeautifulSoup4 pdfplumber pandas pypdf2 fpdf2 numpy==1.18.0
    - name: Download and Preprocess missing lines
      run: |
        python3 auto_dl_process.py
    - name: Commit pdf
      run: |
        git config --local user.email "amouro@gmail.com"
        git config --local user.name "amouro"
        git add component
        git add pdf
        git diff-index --quiet HEAD || git commit -m "[BOT] Update processed pdf"
    - name: Build Summary CSV
      run: |
        python3 auto_summary_parser.py
    - name: Commit files
      run: |
        git config --local user.email "amouro@gmail.com"
        git config --local user.name "amouro"
        git add component
        git add data
        git add pdf
        git diff-index --quiet HEAD || git commit -m "[BOT] Update auto_output.csv"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.extract_branch.outputs.branch }}

