name: Extract PDF data

on:
  push:
    branches:
      - development

jobs:
  build:
    name: Extract data from PDF to CSV
    runs-on: macos-latest

    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install pdfplumber pandas BeautifulSoup4 requests
    - name: Build and publish
      run: |
        python3 download_report.py
    - name: Commit files
      run: |
        git config --local user.email "amouro@gmail.com"
        git config --local user.name "amouro"
        git add data
        git add pdf
        git commit -m "[BOT] Update output.csv"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.extract_branch.outputs.branch }}

